### ISSUE TITLE
project-f.rst (and likely others): broken link

### ISSUE THREAD

**Issue by mpictor** [chipsalliance/f4pga-examples#304]
[project-f.rst](https://github.com/chipsalliance/f4pga-examples/blob/main/docs/project-f.rst) ([project-f.html](https://f4pga-examples.readthedocs.io/en/latest/project-f.html)) has a bad link in the warning at the top.

The link to 
`https://github.com/chipsalliance/f4pga-arch-defs/issues/2246` should instead point to 
`https://github.com/SymbiFlow/f4pga-arch-defs/issues/2246`. (or has the link been updated but the repo hasn't moved yet?)

I suspect a global search-and-replace for links to chipsalliance/f4pga-arch-defs will find other occurrences of links that are broken.

**Comment by umarcor** [comment]
> has the link been updated but the repo hasn't moved yet?

That is the case. Nonetheless, see #305.
