### ISSUE TITLE
Unable to handle Shift with Ternary operator

### ISSUE THREAD

**Issue by westonMS** [chipsalliance/f4pga-examples#314]
# Shift-Ternary Bug

Using Surelog plugin, with Yosys, Yosys gives the following bug  
`ERROR: Unsupported expression in mark_as_unsigned!`

Yosys parser is able to compile the program without using Surelog

The error is caused by a shift operator followed by a ternary operator. Shifting either directions causes the bug. So does the `<<<` or `>>>` shift operator.
Problem Statement : `(0)<<(0)?(0):(0);`

Simplified code that causes error:
```
module top();
logic x;
assign x = (0)<<((0)?(0):(0));
endmodule
```
Source code generated using [Verismith](https://github.com/ymherklotz/verismith)

**Comment by westonMS** [comment]
If the Ternary operation is not in parenthesis, the bug will not occur

**Comment by Zach227** [comment]
I've retested this bug with the latest install and have verified that it is fixed.

**Comment by umarcor** [comment]
@Zach227 the environment for xc7 was updated very few hours ago: https://github.com/chipsalliance/f4pga-examples/commits/main. Did you fetch and pull the latest changes from the main branch 2h ago (when you wrote the comment)?

**Comment by Zach227** [comment]
I retested this with the latest update and the issue is now resolved.
